CC=icc -restrict -std=c99
CXX=icpc -restrict

FC=

flags = -O3 -ip
vecflags = -vec -xAVX2
novecflags = -no-vec

omp_flags+=-fopenmp

ifdef VEC_REPORT
vecflags+=-qopt-report=5 -qopt-report-phase=vec
endif
